### ISSUE TITLE
model-server is not starting

### ISSUE THREAD

**Issue by mhmtsrfglu** [modelix/modelix.core#2]
Hi,

I  just try to run model-server with `../gradlew run` command. But it does not start. I always got an error related with keycloak.

`11:11:11.517 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.modelix.authorization.KtorAuthUtilsKt$installAuthentication$1$3.invoke(KtorAuthUtils.kt:55)
        at org.modelix.authorization.KtorAuthUtilsKt$installAuthentication$1$3.invoke(KtorAuthUtils.kt:54)
        at io.ktor.server.auth.jwt.JWTAuthKt.jwt(JWTAuth.kt:326)
        at org.modelix.authorization.KtorAuthUtilsKt$installAuthentication$1.invoke(KtorAuthUtils.kt:54)
        at org.modelix.authorization.KtorAuthUtilsKt$installAuthentication$1.invoke(KtorAuthUtils.kt:41)
        at io.ktor.server.auth.Authentication$Companion.install(Authentication.kt:98)
        at io.ktor.server.auth.Authentication$Companion.install(Authentication.kt:94)
        at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:98)
        at org.modelix.authorization.KtorAuthUtilsKt.installAuthentication(KtorAuthUtils.kt:41)
        at org.modelix.model.server.Main$main$ktorServer$1.invoke(Main.kt:247)
        at org.modelix.model.server.Main$main$ktorServer$1.invoke(Main.kt:245)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:323)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:340)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:312)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:149)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:279)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:185)
        at org.modelix.model.server.Main.main(Main.kt:290)
Caused by: java.lang.IllegalArgumentException: Configuration URL can not be null.
        at org.keycloak.authorization.client.AuthzClient.<init>(AuthzClient.java:253)
        at org.keycloak.authorization.client.AuthzClient.create(AuthzClient.java:94)
        at org.modelix.authorization.KeycloakUtils.<clinit>(KeycloakUtils.kt:35)
        ... 19 more
[11:11:20] New version is available at ignite.apache.org: 2.14.0
<============-> 94% EXECUTING [1m 21s]
> :model-server:run` 

Is there any solution ?

![Screenshot_1](https://user-images.githubusercontent.com/14332405/194834931-89b2cf4b-5207-49da-ab91-10d6b389fcde.png)

**Comment by nkoester** [comment]
We fixed this soon after reporting but forgot to mention it here. Please try again.

**Comment by mhmtsrfglu** [comment]
> 

Yes, it is working without any problem. Thank you
